# Generated by Django 4.2.5 on 2023-09-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='intentos',
            field=models.IntegerField(default=0),
        ),
    ]
